### ISSUE TITLE
履歴が表示されない

### ISSUE THREAD

**Issue by ryutaro** [ryutaro/Hayaemon_Web#15]
履歴で月を選択すると履歴が表示されなくなるみたい

**Comment by arigayas** [comment]
別のissueに登録すべきかもですが、全部の月の履歴部分の冒頭に

「1
このバージョンをダウンロード」

と言うのが付いてしまってます。

**Comment by arigayas** [comment]
最初の要素？に
`<div class='history'>`が無いためにスタイルが無効に（文字が大きく）なってる


![image](https://user-images.githubusercontent.com/11251874/44005728-1c348098-9eb3-11e8-93db-c9b7ad2b00a2.png)
