### ISSUE TITLE
PHP 版の donate では、フッターのパンくずリストの要素が1つ消えてる。

### ISSUE THREAD

**Issue by arigayas** [ryutaro/Hayaemon_Web#16]
### donate.html
![image](https://user-images.githubusercontent.com/11251874/44004784-762593cc-9ea3-11e8-9027-01d237685326.png)
index ＞bosyu ＞ donate

### donate.php
![image](https://user-images.githubusercontent.com/11251874/44004798-abcf21b4-9ea3-11e8-865b-e83585ac7130.png)
index ＞ donate

**Comment by ryutaro** [comment]
Ohそれは気がつかなかったな・・・ 二つ以上のパンクズリストがあることを考慮してなかったので 設計から見直す必要があるかも

このページだけしか存在しないなら直接埋め込む事も視野

**Comment by arigayas** [comment]
確か 二つ以上のパンクズリストは、このページのみなので直接書くのが良いかもです。

**Comment by ryutaro** [comment]
次の2ページでパンクズリストが2つでした
http://hayaemon.jp/introduce.html
http://hayaemon.jp/donate.html

**Comment by arigayas** [comment]
確認していただきありがとうございます。
