### ISSUE TITLE
リンクの後ろのボタンの色の変更の提案

### ISSUE THREAD

**Issue by arigayas** [ryutaro/Hayaemon_Web#17]
### http://hayaemon.jp
![image](https://user-images.githubusercontent.com/11251874/44005581-9d97c8f0-9eb0-11e8-962b-96ec43555ff7.png)

### 現状の色
![image](https://user-images.githubusercontent.com/11251874/44005606-e19843c2-9eb0-11e8-897f-5172965c1236.png)

### color: #3e618d;
![image](https://user-images.githubusercontent.com/11251874/44005618-2117c66c-9eb1-11e8-8657-e02e8e17cbbb.png)

### color: #8fb4e1;
![image](https://user-images.githubusercontent.com/11251874/44005635-6400ee0e-9eb1-11e8-859f-31165c174153.png)

**Comment by ryutaro** [comment]
背景が白なので暗い方がコントラスト比が高くなって見やすそうですね

**Comment by ryotayama** [comment]
自分も暗い方がいいかなーと思うけど、ピンポイントでしか見れないから、実際に当てはめてみたときの全体像が見たいですね₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
## #3e618d;
![image](https://user-images.githubusercontent.com/11251874/44032981-dec56600-9f43-11e8-9d25-78f78cbe01c4.png)

## #8fb4e1;
![image](https://user-images.githubusercontent.com/11251874/44033078-2e53ce32-9f44-11e8-986c-9b87a08708d5.png)

**Comment by ryotayama** [comment]
ありがとー！！
やっぱ暗いほういいね₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
暗い方の#3e618d;にしますね。
