### ISSUE TITLE
bosyu.php GitHubへのリンク文字列の後ろの画像をGitHubのアイコンに変更するのを提案します。

### ISSUE THREAD

**Issue by arigayas** [ryutaro/Hayaemon_Web#25]
### 現状 content: '\f138';
![image](https://user-images.githubusercontent.com/11251874/44112584-6626d1e0-a040-11e8-84f7-53fda9596c51.png)

### content: '\f126'; // code-branch
![image](https://user-images.githubusercontent.com/11251874/44112932-8106104c-a041-11e8-8294-86916a3135c1.png)
.github::after{
    content: "\f126";
    font-family:"Font Awesome 5 Free";
    font-smoothing: antialiased;
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    line-height: 1;
}

**Comment by arigayas** [comment]
### content: '\f09b'; // github
![image](https://user-images.githubusercontent.com/11251874/44115890-f430a5ac-a049-11e8-8186-ddf7d4761cb5.png)

.github::after{
    content: "\f09b";
    font-family:"Font Awesome 5 Brands";
    font-smoothing: antialiased;
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    line-height: 1;
}

**Comment by arigayas** [comment]
### content: '\f092'; // github-square
![image](https://user-images.githubusercontent.com/11251874/44116050-64706604-a04a-11e8-804f-c926cf82f855.png)
.github::after{
    content: "\f092";
    font-family:"Font Awesome 5 Brands";
    font-smoothing: antialiased;
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    line-height: 1;
}

**Comment by arigayas** [comment]
### content: '\f113'; // github-alt
![image](https://user-images.githubusercontent.com/11251874/44116129-a19f19da-a04a-11e8-987d-31908f5f493e.png)
.github::after{
    content: "\f113";
    font-family:"Font Awesome 5 Brands";
    font-smoothing: antialiased;
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    line-height: 1;
}

以上です。
_アイコンが出なくてハマった_

**Comment by ryotayama** [comment]
いいね！！
個人的にはf09bが好きです！！

**Comment by ryutaro** [comment]
> リンク先が :github: の場合のピクトグラムについてアンケートです
リアクションで回答してください
:kirby: <https://user-images.githubusercontent.com/11251874/44112932-8106104c-a041-11e8-8294-86916a3135c1.png>
:eevee: <https://user-images.githubusercontent.com/11251874/44115890-f430a5ac-a049-11e8-8186-ddf7d4761cb5.png>
:pikachu: <https://user-images.githubusercontent.com/11251874/44116050-64706604-a04a-11e8-804f-c926cf82f855.png>
:goomba: <https://user-images.githubusercontent.com/11251874/44116129-a19f19da-a04a-11e8-987d-31908f5f493e.png>
<sub>[View in Slack](https://hayaemon.slack.com/archives/CC714QP29/p1534323366000100)</sub>

**Comment by arigayas** [comment]
![image](https://user-images.githubusercontent.com/11251874/44169951-de8aff00-a110-11e8-9ce7-4c9b14989269.png)

Slackで試しにGitHubのアイコンを前に持ってきて「GitHub」を消して見るのはどうかな？
という提案があったので作ってみた。
