### ISSUE TITLE
history.php TwitterIDへのリンクが正しくない

### ISSUE THREAD

**Issue by arigayas** [ryutaro/Hayaemon_Web#31]
hayaemon/history.php?date=201805

例えば、2018/05/11 MacOS Version 0.01 β1 開発版公開 の
Daisukeさん（Twitter: @DaisukeAtraxia2）のURLが hayaemon/https://twitter.com/DaisukeAtraxia2 となっている。

**Comment by arigayas** [comment]
733463a の修正は表示される文字列が

###  Daisukeさん（Twitter: @DaisukeAtraxia2）が有志で開発してくれました。
とならずに
###  @DaisukeAtraxia2
となっています。

**Comment by arigayas** [comment]
リンクは正しくhttps://twitter.com/DaisukeAtraxia2 となりましたが・・・。

**Comment by ryutaro** [comment]
この問題は現に解決されています、該当の問題は別の問題であるため別のissueを新しくオープンしてください

**Comment by arigayas** [comment]
わかりました。
