### ISSUE TITLE
<br/>や<br />を<br>に統一する。

### ISSUE THREAD

**Issue by arigayas** [ryutaro/Hayaemon_Web#32]
### 関連するissue
#29 HTML5 に移行する

**Comment by ryutaro** [comment]
というかbrは改行であって幅調整用のタグじゃないから消しましょう

**Comment by arigayas** [comment]
各ファイルの最後の
`<?php`
`include('./include/footer.php');`
`?>`
の直前にある`<br>`は消しても良いかもね。
実行するならこのissueじゃなく新しくissue登録することになりますが。
