### ISSUE TITLE
メールフォームの /cgi-bin/postmail.cgi がリポジトリに存在していません。

### ISSUE THREAD

**Issue by arigayas** [ryutaro/Hayaemon_Web#33]
/cgi-bin/postmail.cgi へのリンクがあるのが、

- index.php
- manual.php
- uninstall.php

_メールフォームをPHPで書くのもアリかもしれません。_

**Comment by ryutaro** [comment]
ありさん書いてくれるの？

**Comment by arigayas** [comment]
書けませぬ・・・。

**Comment by ryutaro** [comment]
もれなく僕が書く流れですか...

**Comment by arigayas** [comment]
いやぁ @ryotayama さんがリポジトリにpushしてくれれば良いと思っては居ます。

**Comment by ryutaro** [comment]
いやまぁメール送信するくらいすぐ作れるけど、問題は今どんな機能があってどんなメールが来てるかわからないところですね
というか"メール"である必要があるのかって所ですね

**Comment by arigayas** [comment]
メールフォームに送られてくる内容は良太さんに聞かないと ほぼ分からないから待ち状態ですね(´・ω・`)

**Comment by arigayas** [comment]
https://github.com/ryotayama/Hayaemon_Web/issues/9 メールフォームをGoogleフォームに移行する
が決定なら、このissueは閉じても良いかな？

**Comment by ryotayama** [comment]
メールは埋もれがちだったり色々問題があるので、決定にしましょう！
ただ、導入するまでに時間がかかると思うので必要であればpostmail.cgiをあげるのは構いませんが、ソース内にパスワードとかが書かれてたような気もするので要注意ですね。

**Comment by ryutaro** [comment]
postmail.cgiのバージョンが古くメンテナンスもされていない事から採用を取り止めます。
以上の理由から本トピックスはクローズします。

以下はオフトピックです
