### ISSUE TITLE
header.php 「聞々ハヤえもん公式サイト」の「聞々」にrubyタグを付けたい。

### ISSUE THREAD

**Issue by arigayas** [ryutaro/Hayaemon_Web#36]
### 現状の出力されるhtml
`<h1>`
`    <span class="font13">ぶ ん ぶ ん</span><br/>`
`    聞々ハヤえもん公式サイト`　←　header.phpでは `<?php echo $o['GlobalTitle']; ?>` となっています。
`</h1>`

![image](https://user-images.githubusercontent.com/11251874/44597452-a3708600-a80a-11e8-9359-bc23b5e4d23d.png)

### rubyタグ付与後出力されるhtml
`<h1>`
`    <ruby>聞々<rp>(</rp><rt>ぶんぶん</rt><rp>)</rp></ruby>ハヤえもん公式サイト`
`</h1>`

![image](https://user-images.githubusercontent.com/11251874/44597507-d6b31500-a80a-11e8-9e50-80cfcfd8a5ef.png)

影響としてはconfigファイルにページヘッダー(ruby)用の変数を増やす必要がある。

**Comment by arigayas** [comment]
CSSに「, #banner ruby」を追加する必要もありました。
#banner h1, #banner ruby {
	margin-left: 110px;
	font-weight: bold;
	color: #ff4040;
	font-size: 32px;
	line-height: 70%;
}

**Comment by ryotayama** [comment]
何を意図したコードか明示的になるからいいんじゃないかな！

**Comment by arigayas** [comment]
### rubyタグ付与後出力されるhtml
`<h1>`
`    <ruby>聞々<rp>(</rp><rt>ぶんぶん</rt><rp>)</rp></ruby>ハヤえもん公式サイト`
`</h1>`

### config.inc.phpに以下のようなコードを追加

`$Kanji = '聞々';`
`$yomi = 'ぶんぶん';`
`$set['HeaderTitle'] = '<ruby>'.$Kanji.'<rp>(</rp><rt>'.$yomi.'</rt><rp>)</rp></ruby>ハヤえもん公式サイト';`

### include\header.php
https://github.com/ryutaro/Hayaemon_Web/blob/bd576d79e9e904d3ba95cbe00d7fe6caaea9e864/include/header.php#L83-L84
を
`                <?php echo $o['HeaderTitle']; ?>`
に置き換える。


### 以下はオフトピですが、
config.inc.php の
「ハヤえもん公式サイト」を変数に入れたくなったけど良い変数名が思い浮かばないです。
「ハヤえもん公式サイト」を変数に入れたら
https://github.com/ryutaro/Hayaemon_Web/blob/bd576d79e9e904d3ba95cbe00d7fe6caaea9e864/config.inc.php#L27
$set['GlobalTitle'] = '聞々ハヤえもん公式サイト'; を
$set['GlobalTitle'] = $Kanji.$hoge; に出来るなぁと思っただけなのですが。
