### ISSUE TITLE
聞々ハヤえもんユーザーコミュニティがリンク切れ

### ISSUE THREAD

**Issue by ryutaro** [ryutaro/Hayaemon_Web#47]
http://hayaemon.jp/manual.html
からリンクされている聞々ハヤえもんユーザーコミュニティがリンク切れしています
リンク先は
http://hayaemon.jp/wiki/

**Comment by ryutaro** [comment]
これWiki運用しますか？それともリンク外しますか？

**Comment by ryotayama** [comment]
もう有効に運用されてないので、リンク外しましょう！

**Comment by ryutaro** [comment]
了解です

**Comment by arigayas** [comment]
### ①聞々ハヤえもんユーザーコミュニティで質問する。
聞々ハヤえもんユーザーコミュニティには、「質問」というカテゴリが存在している為、そちらにご投稿ください。開発者であるりょーた、または、親切なユーザー様から答えが得られるかもしれません。

聞々ハヤえもんユーザーコミュニティ

----

Twitterでのやりとりすると うんたらかんたらって書き換えるのはどうでしょうか？

**Comment by arigayas** [comment]
参考になればとマニュアルページからコピペ

---
≪マニュアルを読んでも分からないことがあった場合≫
マニュアルを読んでも分からないことがあった場合は、下記の方法でお問い合わせいただく事ができます。

### ①聞々ハヤえもんユーザーコミュニティで質問する。
省略

### ②開発者にメールを送ってみる。
開発者であるりょーたに直接の質問がある場合は、`良太さんのメルアド`までメールをお送りください。

### ③メールフォームから質問してみる。
下記のメールフォームからも簡単にメールをお送りいただく事ができます。返信が必要な場合は、あなたのメールアドレスを併せてご記入ください。

**Comment by ryotayama** [comment]
ぜひそうしましょう！
こんな感じで٩( ᐛ )و

①ツイッターで質問する。
開発者は日頃ツイッターにいる事が多い為、ツイッターで質問いただく事ができます。

**Comment by arigayas** [comment]
こんな感じにしました。(スクリーンショットです)

![image](https://user-images.githubusercontent.com/11251874/50372661-cd4d8400-0615-11e9-9da9-d0ebd9b7c688.png)

**Comment by ryotayama** [comment]
ありさん、ありがとう٩( ᐛ )و
