### ISSUE TITLE
thanks.php WIkiページへのリンクを削除する

### ISSUE THREAD

**Issue by arigayas** [ryutaro/Hayaemon_Web#56]
参考：http://hayaemon.jp/thanks.html
関連するissue：#47
WIkiページへのリンク「聞々ハヤえもんユーザーコミュニティはこちら」が2箇所ありますが、
ただ単純に削除するのも、何だかなぁと思うので良い文言をいただけたらありがたいです。
面倒ならWIkiページへのリンクをサックリ削除でも良いですがw

## 参考ページからの以下転載です。

---

### 開発者に感想を伝えてみる。
何気ない「ありがとう」が、最大のモチベーションに。
もし聞々ハヤえもんを気に入っていただけたら、感想をお聞かせください。

感想をいただくことで開発意欲があがり、さらに良いソフトを作るためのモチベーションにつながります。

聞々ハヤえもんユーザーコミュニティはこちら
### アイデアや不具合報告を投稿。
新しいバージョンを、さらに新しく。
「もっとこんな機能が欲しい！」と思うような機能や、「あれ？　これって不具合では？」と思うようなことがあったら、すぐに聞々ハヤえもんユーザーコミュニティにご投稿ください。

これまでにも、聞々ハヤえもんユーザーコミュニティへの投稿から200回にも及ぶバージョンアップが行われています。

あなたのご意見によって、聞々ハヤえもんはよりよいソフトへと成長していきます。

聞々ハヤえもんユーザーコミュニティはこちら

**Comment by ryotayama** [comment]
これでどーかなぁ٩( ᐛ )و

開発者に感想を伝えてみる。
何気ない「ありがとう」が、最大のモチベーションに。
もし聞々ハヤえもんを気に入っていただけたら、感想をお聞かせください。

感想をいただくことで開発意欲があがり、さらに良いソフトを作るためのモチベーションにつながります。

開発者と連絡が取れるツイッターはこちら

アイデアや不具合報告を投稿。
新しいバージョンを、さらに新しく。
「もっとこんな機能が欲しい！」と思うような機能や、「あれ？　これって不具合では？」と思うようなことがあったら、すぐに開発者までお知らせください。

あなたのご意見によって、聞々ハヤえもんはよりよいソフトへと成長していきます。

開発者と連絡が取れるツイッターはこちら

**Comment by arigayas** [comment]
ありがとうございます。
良太さんのコメントを反映させますね。

リンクはどの部分にしましょう？

1. 開発者と連絡が取れるツイッターは[こちら](https://twitter.com/ryota_yama)
2. 開発者と連絡が取れる[ツイッターはこちら](https://twitter.com/ryota_yama)

**Comment by ryotayama** [comment]
他のリンクと整合性を合わせようと思うと、「開発者」から全部をリンクかなぁ？？

**Comment by arigayas** [comment]
わかりました。1行丸っとリンクにしてTwitterアイコンが付くようにしますね。

↓開発者募集ページのリンクのスクリーンショット
![image](https://user-images.githubusercontent.com/11251874/50372002-54482f80-0609-11e9-94a0-bec178c8f1a6.png)
